import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './componenets/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='py-6 px-12 h-screen'>
          <div className='w-full h-full overflow-scroll border-8 border-black rounded-2xl'>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
